import type { Metadata } from "next";
import { Noto_Sans, Hind } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/components/shared/Provider";

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-noto",
});
const hind = Hind({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-hind",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons:{
  //   icon: '/assets/icons/logo1.png'
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen dark font-inter antialiased",
          // chakra.variable,
          noto.variable,
          hind.variable
        )}
      >
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
