import type { Metadata } from "next";
import { Inter, Chakra_Petch, Rajdhani, Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

// const chakra = Chakra_Petch({
//   subsets: ["latin"],
//   weight: ["300", "400", "700"],
//   variable: "--font-chakra",
// });

const inter = Noto_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons:{
  //   icon: '/assets/icons/logo1.png'
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen dark font-inter antialiased",
          // chakra.variable,
          inter.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
